// @ts-check
/** @type {import("tailwindcss/types").Config } */
module.exports = {
  content: [
    './node_modules/pliny/**/*.js',
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,tsx}',
    './components/**/*.{js,ts,tsx}',
    './layouts/**/*.{js,ts,tsx}',
    './data/**/*.mdx',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        mono: ['var(--font-jetbrains-mono)', 'Menlo', 'monospace'],
        sans: ['var(--font-jetbrains-mono)', 'Menlo', 'monospace'],
        heading: ['var(--font-jetbrains-mono)', 'Menlo', 'monospace'],
      },
      colors: {
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#574140',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        outline: '#8b7170',
        'outline-variant': '#debfbe',
        'surface-tint': '#a83639',
        primary: {
          DEFAULT: '#a83639',
          600: '#a83639',
        },
        gray: {
          50: '#ffffff',
          100: '#f2f4f6',
          200: '#eceef0',
          300: '#e0e3e5',
          400: '#8b7170',
          500: '#574140',
          600: '#505f76',
          700: '#191c1e',
          800: '#2d3133',
          900: '#202426',
        },
        'on-primary': '#ffffff',
        'primary-container': '#f87171',
        'on-primary-container': '#6c0513',
        'inverse-primary': '#ffb3b0',
        secondary: '#545f73',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e0f8',
        'on-secondary-container': '#586377',
        tertiary: '#505f76',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8d9db5',
        'on-tertiary-container': '#243449',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b0',
        'on-primary-fixed': '#410006',
        'on-primary-fixed-variant': '#881d24',
        'secondary-fixed': '#d8e3fb',
        'secondary-fixed-dim': '#bcc7de',
        'on-secondary-fixed': '#111c2d',
        'on-secondary-fixed-variant': '#3c475a',
        'tertiary-fixed': '#d3e4fe',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-tertiary-fixed': '#0b1c30',
        'on-tertiary-fixed-variant': '#38485d',
        background: '#f7f9fb',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
      },
      fontSize: {
        'headline-lg': [
          '2rem',
          { lineHeight: '2.5rem', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-lg-mobile': [
          '1.5rem',
          { lineHeight: '2rem', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.05em', fontWeight: '500' }],
        'code-inline': ['0.8125rem', { lineHeight: '1.125rem', fontWeight: '400' }],
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            fontFamily: theme('fontFamily.sans').join(', '),
            color: theme('colors.on-surface'),
            p: {
              fontSize: '1rem',
              lineHeight: '1.5rem',
              marginTop: '0.75em',
              marginBottom: '0.75em',
            },
            'ul, ol': { fontSize: '1rem', lineHeight: '1.5rem' },
            'h1,h2,h3,h4,h5,h6': {
              fontFamily: theme('fontFamily.heading').join(', '),
              fontWeight: '600',
              letterSpacing: '-0.02em',
            },
            a: {
              color: theme('colors.primary.DEFAULT'),
              fontWeight: '500',
              textDecorationColor: theme('colors.primary-container'),
            },
            code: {
              fontFamily: theme('fontFamily.mono').join(', '),
              color: theme('colors.on-surface'),
              backgroundColor: theme('colors.surface-container'),
              fontSize: '0.8125rem',
              lineHeight: '1.125rem',
              fontWeight: '400',
              padding: '0.125rem 0.25rem',
              borderRadius: '0',
            },
            'code::before': { content: 'none' },
            'code::after': { content: 'none' },
            'pre code': { backgroundColor: 'transparent', padding: '0' },
            img: {
              marginTop: '1em',
              marginBottom: '0.5em',
              borderRadius: '0',
              border: `1px solid ${theme('colors.outline-variant')}`,
              boxShadow: 'none',
            },
            figcaption: {
              marginTop: '0.375em',
              fontSize: '0.75rem',
              lineHeight: '1rem',
              letterSpacing: '0.05em',
              textTransform: 'uppercase',
              color: theme('colors.tertiary'),
            },
            table: { fontSize: '0.875rem', lineHeight: '1.25rem' },
            thead: { borderBottomColor: theme('colors.outline') },
            'tbody tr': { borderBottomColor: theme('colors.outline-variant') },
            'tbody tr:nth-child(even)': { backgroundColor: theme('colors.surface-container-low') },
          },
        },
        invert: {
          css: {
            '--tw-prose-body': theme('colors.inverse-on-surface'),
            '--tw-prose-headings': theme('colors.inverse-on-surface'),
            '--tw-prose-links': theme('colors.inverse-primary'),
            '--tw-prose-code': theme('colors.inverse-on-surface'),
            '--tw-prose-pre-bg': '#202426',
            '--tw-prose-hr': '#574140',
            '--tw-prose-th-borders': '#8b7170',
            '--tw-prose-td-borders': '#574140',
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
}
